apiVersion: v1
kind: Service
metadata:
  labels:
    run: aidoc-service
  name: aidoc-service
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: aidoc-deployment
